### PR TITLE
Implement cluster connection.

### PR DESCRIPTION
**Pull request by YoEight**

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@YoEight FYI, https://github.com/grpc/grpc-java/issues/7133 - Here is an example of how I register a name resolver in my fs2 based [client](https://github.com/ahjohannessen/sec/blob/9ea98e1e63d79a9c4fc4d40f012a180fcd8d06de/core/src/main/scala/sec/api/cluster/watch.scala#L36).

**Comment by YoEight** [comment]
Thanks for the pointer @ahjohannessen

**Comment by YoEight** [comment]
I addressed the deprecation warning.

**Review by hayley-jean — APPROVED** [review]
Looks good 👍 
Only thing to note currently is that the client needs to catch `NotLeaderException`, and dispose and reconnect the connection to connect to the new leader.

**Pull request merged**
